version: '3.3'

networks:
  todo_network:
    driver: bridge
    
services: 
  webapp:
    build:
      context: .
      dockerfile: ./WebApp/Dockerfile
    ports:
      - "8081:80"
    depends_on: 
      - "db"
    environment:
      DB_CONNECTION_STRING: "host=${DB_HOST};port=${DB_PORT};database=${DB_DATABASE};username=${DB_USERNAME};password=${DB_PASSWORD};"
    networks: 
      - todo_network
        
  webapi:
    build:
      context: .
      dockerfile: ./WebAPI/Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - "db"
    environment:
      DB_CONNECTION_STRING: "host=${DB_HOST};port=${DB_PORT};database=${DB_DATABASE};username=${DB_USERNAME};password=${DB_PASSWORD};"
    networks:
      - todo_network
        
  db:
    image: postgres:latest
    ports:
      - "5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./DbScripts:/scripts
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
#    command:
#      - psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -a -f scripts/migration.sql
    networks: 
      - todo_network
    restart: always
volumes: 
  db_data:
